# CRYSTAL: Xi108:W2:A1:S13 | face=S | node=84 | depth=2 | phase=Cardinal
# METRO: Me
# BRIDGES: Xi108:W2:A1:S12→Xi108:W2:A1:S14→Xi108:W1:A1:S13→Xi108:W3:A1:S13→Xi108:W2:A2:S13

"""
ATHENA OS - BIT4
================
Symmetry, Involutions, and the Klein Four Group

From BIT4.docx §3:

DISTINGUISHED INVOLUTIONS:

1. TRUTH-NEGATION (¬) - Bit-flip on supports:
    ¬x := {1-b | b ∈ x}
    ¬0 = 1, ¬1 = 0, ¬⊥ = ⊥, ¬⊤ = ⊤

2. CONFLATION / SHADOW SWAP (κ):
    κ(⊥) = ⊤, κ(⊤) = ⊥, κ(0) = 0, κ(1) = 1

3. SET COMPLEMENT (~):
    ~x := {0,1} \ x
    ~⊥ = ⊤, ~⊤ = ⊥, ~0 = 1, ~1 = 0

KLEIN RELATIONS:
    ¬ ∘ κ = κ ∘ ¬ = ~
    
    {id, ¬, κ, ~} ≅ V₄ (Klein four group)

ORDER BEHAVIOR:
    ¬: automorphism of ≤_k, anti-automorphism of ≤_t
    κ: anti-automorphism of ≤_k, automorphism of ≤_t
    ~: anti-automorphism of both ≤_k and ≤_t

ADMISSIBLE SYMMETRIES:
    Adm(B₄) = {id, ¬, κ, ~} ≅ V₄
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Callable, Dict, List, Set, Tuple
from enum import Enum

from .carrier import B4, TwoRail

# =============================================================================
# INVOLUTIONS
# =============================================================================

def neg(x: B4) -> B4:
    """
    Truth-negation (bit-flip): ¬x := {1-b | b ∈ x}
    
    ¬0 = 1, ¬1 = 0, ¬⊥ = ⊥, ¬⊤ = ⊤
    """
    flipped = frozenset(1 - b for b in x.support)
    return B4.from_support(flipped)

def kappa(x: B4) -> B4:
    """
    Conflation / shadow swap: κ
    
    κ(⊥) = ⊤, κ(⊤) = ⊥, κ(0) = 0, κ(1) = 1
    
    Swaps gap and conflict while preserving classical values.
    """
    if x == B4.BOT:
        return B4.TOP
    elif x == B4.TOP:
        return B4.BOT
    else:
        return x

def complement(x: B4) -> B4:
    """
    Set complement: ~x := {0,1} \ x
    
    ~⊥ = ⊤, ~⊤ = ⊥, ~0 = 1, ~1 = 0
    """
    full = frozenset({0, 1})
    return B4.from_support(full - x.support)

def identity(x: B4) -> B4:
    """Identity function: id(x) = x"""
    return x

# Aliases
NOT = neg            # ¬
SWAP = kappa         # κ
COMP = complement    # ~
ID = identity        # id

# =============================================================================
# KLEIN FOUR GROUP
# =============================================================================

class KleinElement(Enum):
    """Elements of the Klein four group V₄."""
    
    ID = "id"      # Identity
    NEG = "neg"    # Truth-negation ¬
    KAPPA = "kappa"  # Conflation κ
    COMP = "comp"  # Set complement ~

# Group operation table for V₄
# Composition: a ∘ b means apply b first, then a
KLEIN_TABLE: Dict[Tuple[KleinElement, KleinElement], KleinElement] = {
    # id ∘ x = x
    (KleinElement.ID, KleinElement.ID): KleinElement.ID,
    (KleinElement.ID, KleinElement.NEG): KleinElement.NEG,
    (KleinElement.ID, KleinElement.KAPPA): KleinElement.KAPPA,
    (KleinElement.ID, KleinElement.COMP): KleinElement.COMP,
    
    # ¬ ∘ x
    (KleinElement.NEG, KleinElement.ID): KleinElement.NEG,
    (KleinElement.NEG, KleinElement.NEG): KleinElement.ID,
    (KleinElement.NEG, KleinElement.KAPPA): KleinElement.COMP,
    (KleinElement.NEG, KleinElement.COMP): KleinElement.KAPPA,
    
    # κ ∘ x
    (KleinElement.KAPPA, KleinElement.ID): KleinElement.KAPPA,
    (KleinElement.KAPPA, KleinElement.NEG): KleinElement.COMP,
    (KleinElement.KAPPA, KleinElement.KAPPA): KleinElement.ID,
    (KleinElement.KAPPA, KleinElement.COMP): KleinElement.NEG,
    
    # ~ ∘ x
    (KleinElement.COMP, KleinElement.ID): KleinElement.COMP,
    (KleinElement.COMP, KleinElement.NEG): KleinElement.KAPPA,
    (KleinElement.COMP, KleinElement.KAPPA): KleinElement.NEG,
    (KleinElement.COMP, KleinElement.COMP): KleinElement.ID,
}

def klein_compose(a: KleinElement, b: KleinElement) -> KleinElement:
    """Compose two Klein group elements: a ∘ b (apply b first)."""
    return KLEIN_TABLE[(a, b)]

def klein_inverse(a: KleinElement) -> KleinElement:
    """
    Inverse of Klein group element.
    
    Every element is its own inverse (all involutions).
    """
    return a

def klein_apply(elem: KleinElement, x: B4) -> B4:
    """Apply Klein group element as B4 transformation."""
    funcs = {
        KleinElement.ID: identity,
        KleinElement.NEG: neg,
        KleinElement.KAPPA: kappa,
        KleinElement.COMP: complement
    }
    return funcs[elem](x)

# =============================================================================
# DIHEDRAL GROUP D₄ (Extended symmetries)
# =============================================================================

@dataclass
class DihedralElement:
    """
    Element of D₄ acting on B₄.
    
    D₄ is generated by V₄ plus the rotation r: (⊥ → 0 → ⊤ → 1 → ⊥)
    """
    
    klein: KleinElement
    rotation: int  # 0, 1, 2, or 3 (mod 4)
    
    def apply(self, x: B4) -> B4:
        """Apply D₄ element to B4 value."""
        # First apply Klein component
        result = klein_apply(self.klein, x)
        
        # Then apply rotation
        # Rotation order: ⊥ → 0 → ⊤ → 1 → ⊥
        cycle = [B4.BOT, B4.ZERO, B4.TOP, B4.ONE]
        idx = cycle.index(result)
        rotated_idx = (idx + self.rotation) % 4
        
        return cycle[rotated_idx]

# =============================================================================
# AUTOMORPHISM CLASSIFICATION
# =============================================================================

def is_k_automorphism(f: Callable[[B4], B4]) -> bool:
    """
    Check if f is a ≤_k automorphism.
    
    f preserves knowledge order in both directions.
    """
    from .orders import leq_k
    
    all_values = [B4.BOT, B4.ZERO, B4.ONE, B4.TOP]
    
    # Check bijection
    images = [f(x) for x in all_values]
    if len(set(images)) != 4:
        return False
    
    # Check order preservation
    for x in all_values:
        for y in all_values:
            if leq_k(x, y) != leq_k(f(x), f(y)):
                return False
    
    return True

def is_k_anti_automorphism(f: Callable[[B4], B4]) -> bool:
    """
    Check if f is a ≤_k anti-automorphism.
    
    f reverses knowledge order.
    """
    from .orders import leq_k
    
    all_values = [B4.BOT, B4.ZERO, B4.ONE, B4.TOP]
    
    # Check bijection
    images = [f(x) for x in all_values]
    if len(set(images)) != 4:
        return False
    
    # Check order reversal
    for x in all_values:
        for y in all_values:
            if leq_k(x, y) != leq_k(f(y), f(x)):
                return False
    
    return True

def is_t_automorphism(f: Callable[[B4], B4]) -> bool:
    """Check if f is a ≤_t automorphism."""
    from .orders import leq_t
    
    all_values = [B4.BOT, B4.ZERO, B4.ONE, B4.TOP]
    
    images = [f(x) for x in all_values]
    if len(set(images)) != 4:
        return False
    
    for x in all_values:
        for y in all_values:
            if leq_t(x, y) != leq_t(f(x), f(y)):
                return False
    
    return True

def is_t_anti_automorphism(f: Callable[[B4], B4]) -> bool:
    """Check if f is a ≤_t anti-automorphism."""
    from .orders import leq_t
    
    all_values = [B4.BOT, B4.ZERO, B4.ONE, B4.TOP]
    
    images = [f(x) for x in all_values]
    if len(set(images)) != 4:
        return False
    
    for x in all_values:
        for y in all_values:
            if leq_t(x, y) != leq_t(f(y), f(x)):
                return False
    
    return True

def classify_symmetry(f: Callable[[B4], B4]) -> Dict[str, bool]:
    """
    Classify a permutation of B₄ by its order behavior.
    """
    return {
        "k_auto": is_k_automorphism(f),
        "k_anti": is_k_anti_automorphism(f),
        "t_auto": is_t_automorphism(f),
        "t_anti": is_t_anti_automorphism(f)
    }

# =============================================================================
# ORBIT COMPUTATION
# =============================================================================

def orbit_under_klein(x: B4) -> Set[B4]:
    """Compute orbit of x under Klein group action."""
    return {
        identity(x),
        neg(x),
        kappa(x),
        complement(x)
    }

def orbits_klein() -> List[Set[B4]]:
    """
    Compute all orbits of Klein group on B₄.
    
    Under V₄: {⊥, ⊤} and {0, 1} are orbits.
    """
    seen = set()
    orbits = []
    
    for x in [B4.BOT, B4.ZERO, B4.ONE, B4.TOP]:
        if x not in seen:
            orb = orbit_under_klein(x)
            orbits.append(orb)
            seen.update(orb)
    
    return orbits

# =============================================================================
# INVOLUTION TABLES
# =============================================================================

def print_involution_table() -> str:
    """Generate involution operation tables."""
    values = [B4.BOT, B4.ZERO, B4.ONE, B4.TOP]
    
    lines = ["Involution Tables:"]
    lines.append("")
    
    # Negation
    lines.append("¬ (negation):")
    for x in values:
        lines.append(f"  ¬{x.glyph} = {neg(x).glyph}")
    lines.append("")
    
    # Kappa
    lines.append("κ (conflation):")
    for x in values:
        lines.append(f"  κ({x.glyph}) = {kappa(x).glyph}")
    lines.append("")
    
    # Complement
    lines.append("~ (complement):")
    for x in values:
        lines.append(f"  ~{x.glyph} = {complement(x).glyph}")
    
    return "\n".join(lines)

def print_klein_table() -> str:
    """Generate Klein group composition table."""
    elements = [KleinElement.ID, KleinElement.NEG, KleinElement.KAPPA, KleinElement.COMP]
    names = {"id": "id", "neg": "¬", "kappa": "κ", "comp": "~"}
    
    header = "∘  | " + " ".join(f"{names[e.value]:2}" for e in elements)
    sep = "-" * len(header)
    
    rows = []
    for a in elements:
        cells = [names[klein_compose(a, b).value] for b in elements]
        row = f"{names[a.value]:2} | " + " ".join(f"{c:2}" for c in cells)
        rows.append(row)
    
    return header + "\n" + sep + "\n" + "\n".join(rows)

# =============================================================================
# VALIDATION
# =============================================================================

def validate_symmetry() -> bool:
    """Validate symmetry module."""
    
    # Test negation
    assert neg(B4.BOT) == B4.BOT
    assert neg(B4.ZERO) == B4.ONE
    assert neg(B4.ONE) == B4.ZERO
    assert neg(B4.TOP) == B4.TOP
    
    # Test kappa
    assert kappa(B4.BOT) == B4.TOP
    assert kappa(B4.TOP) == B4.BOT
    assert kappa(B4.ZERO) == B4.ZERO
    assert kappa(B4.ONE) == B4.ONE
    
    # Test complement
    assert complement(B4.BOT) == B4.TOP
    assert complement(B4.TOP) == B4.BOT
    assert complement(B4.ZERO) == B4.ONE
    assert complement(B4.ONE) == B4.ZERO
    
    # Test involution property (f ∘ f = id)
    for x in [B4.BOT, B4.ZERO, B4.ONE, B4.TOP]:
        assert neg(neg(x)) == x
        assert kappa(kappa(x)) == x
        assert complement(complement(x)) == x
    
    # Test Klein relations: ¬ ∘ κ = ~
    for x in [B4.BOT, B4.ZERO, B4.ONE, B4.TOP]:
        assert neg(kappa(x)) == complement(x)
        assert kappa(neg(x)) == complement(x)
    
    # Test Klein group table
    assert klein_compose(KleinElement.NEG, KleinElement.KAPPA) == KleinElement.COMP
    assert klein_compose(KleinElement.KAPPA, KleinElement.NEG) == KleinElement.COMP
    
    # Test order behavior
    # ¬: k-auto, t-anti
    assert is_k_automorphism(neg)
    assert is_t_anti_automorphism(neg)
    
    # κ: k-anti, t-auto
    assert is_k_anti_automorphism(kappa)
    assert is_t_automorphism(kappa)
    
    # ~: k-anti, t-anti
    assert is_k_anti_automorphism(complement)
    assert is_t_anti_automorphism(complement)
    
    # Test orbits
    orbits = orbits_klein()
    assert len(orbits) == 2
    
    return True

if __name__ == "__main__":
    print("Validating BIT4 Symmetry...")
    assert validate_symmetry()
    print("✓ Symmetry module validated")
    
    print("\n" + print_involution_table())
    print("\n--- Klein Group Composition ---")
    print(print_klein_table())
