# CRYSTAL: Xi108:W2:A4:S16 | face=S | node=128 | depth=2 | phase=Cardinal
# METRO: Me
# BRIDGES: Xi108:W2:A4:S15→Xi108:W2:A4:S17→Xi108:W1:A4:S16→Xi108:W3:A4:S16→Xi108:W2:A3:S16→Xi108:W2:A5:S16

"""
ATHENA OS - HDCS: ACTUATOR OPERATORS
====================================
Hamiltonian Modulation and Force Application

THE ACTUATOR (Â):
    Translates classical control signal u(t) into quantum mechanical
    operator Ĥ_ctrl(t) that modifies system dynamics.
    
    This is HAMILTONIAN ENGINEERING.

TOTAL HAMILTONIAN:
    Ĥ_total(t) = Ĥ_sys + Ĥ_ctrl(t)

CONTROL HAMILTONIAN:
    Ĥ_ctrl(t) = Σ_k u_k(t) Ĝ_k
    
    Where Ĝ_k are system generators (Lie algebra elements).

PHYSICAL IMPLEMENTATION:
    - Phase Correction: V̂ = u(t)n̂ (potential shift)
    - Trajectory Correction: P̂ = u(t)p̂ (momentum kick)

FORCE APPLICATION:
    The "Force" applied is the rate of change of the unitary
    operator generated by Ĥ_ctrl.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple, Callable, Any
from enum import Enum, auto
import numpy as np
from scipy import linalg

# =============================================================================
# ACTUATOR TYPES
# =============================================================================

class ActuatorType(Enum):
    """Types of actuators."""
    
    PHASE = "phase"             # Phase modulation
    AMPLITUDE = "amplitude"     # Amplitude modulation
    MOMENTUM = "momentum"       # Momentum kick
    POSITION = "position"       # Position shift
    UNITARY = "unitary"         # General unitary

class ModulationType(Enum):
    """Types of Hamiltonian modulation."""
    
    CONSTANT = "constant"       # DC drive
    HARMONIC = "harmonic"       # Sinusoidal
    PULSE = "pulse"             # Rectangular pulse
    CHIRP = "chirp"             # Frequency sweep
    OPTIMAL = "optimal"         # Optimal control

# =============================================================================
# GENERATOR OPERATORS
# =============================================================================

class GeneratorOperator:
    """
    Generator Operator Ĝ_k.
    
    Elements of the Lie algebra generating the dynamical group.
    Control Hamiltonian: Ĥ_ctrl = Σ u_k(t) Ĝ_k
    """
    
    def __init__(self, dimension: int, generator_type: str = "position"):
        self.dimension = dimension
        self.generator_type = generator_type
        
        # Generator matrix
        self._matrix = self._create_generator()
    
    def _create_generator(self) -> np.ndarray:
        """Create generator matrix based on type."""
        n = self.dimension
        
        if self.generator_type == "position":
            # Position operator (diagonal)
            return np.diag(np.arange(n) - n/2)
        
        elif self.generator_type == "momentum":
            # Momentum operator (tridiagonal)
            G = np.zeros((n, n), dtype=complex)
            for i in range(n - 1):
                G[i, i+1] = -1j * np.sqrt(i+1)
                G[i+1, i] = 1j * np.sqrt(i+1)
            return G
        
        elif self.generator_type == "number":
            # Number operator
            return np.diag(np.arange(n))
        
        elif self.generator_type == "raising":
            # Raising operator a†
            G = np.zeros((n, n), dtype=complex)
            for i in range(n - 1):
                G[i+1, i] = np.sqrt(i+1)
            return G
        
        elif self.generator_type == "lowering":
            # Lowering operator a
            G = np.zeros((n, n), dtype=complex)
            for i in range(n - 1):
                G[i, i+1] = np.sqrt(i+1)
            return G
        
        elif self.generator_type == "phase":
            # Phase operator
            return np.diag(np.exp(1j * 2 * np.pi * np.arange(n) / n))
        
        elif self.generator_type == "sigma_x":
            # Pauli X (if 2D)
            if n == 2:
                return np.array([[0, 1], [1, 0]], dtype=complex)
            return np.eye(n)
        
        elif self.generator_type == "sigma_y":
            # Pauli Y (if 2D)
            if n == 2:
                return np.array([[0, -1j], [1j, 0]], dtype=complex)
            return np.eye(n)
        
        elif self.generator_type == "sigma_z":
            # Pauli Z (if 2D)
            if n == 2:
                return np.array([[1, 0], [0, -1]], dtype=complex)
            return np.diag([1, -1] + [0]*(n-2))
        
        return np.eye(n)
    
    def apply(self, state: np.ndarray, coefficient: float = 1.0) -> np.ndarray:
        """
        Apply generator to state.
        
        Ĝ|Ψ⟩ multiplied by coefficient
        """
        return coefficient * self._matrix @ state
    
    def commutator(self, other: 'GeneratorOperator') -> np.ndarray:
        """
        Compute commutator [Ĝ₁, Ĝ₂] = Ĝ₁Ĝ₂ - Ĝ₂Ĝ₁
        """
        return self._matrix @ other._matrix - other._matrix @ self._matrix
    
    def is_hermitian(self) -> bool:
        """Check if generator is Hermitian."""
        return np.allclose(self._matrix, self._matrix.conj().T)
    
    @property
    def matrix(self) -> np.ndarray:
        return self._matrix.copy()

# =============================================================================
# CONTROL HAMILTONIAN
# =============================================================================

class ControlHamiltonian:
    """
    Control Hamiltonian Ĥ_ctrl(t).
    
    Ĥ_ctrl(t) = Σ_k u_k(t) Ĝ_k
    
    Combines control signals with generator operators
    to modulate system dynamics.
    """
    
    def __init__(self, dimension: int):
        self.dimension = dimension
        
        # Generators and their control signals
        self._generators: List[GeneratorOperator] = []
        self._control_signals: List[Callable[[float], float]] = []
        
        # Current Hamiltonian matrix
        self._matrix = np.zeros((dimension, dimension), dtype=complex)
    
    def add_control_channel(self, generator: GeneratorOperator,
                           control_signal: Callable[[float], float] = None) -> None:
        """
        Add a control channel.
        
        Ĥ_ctrl += u(t) Ĝ
        """
        self._generators.append(generator)
        
        if control_signal is None:
            control_signal = lambda t: 0.0
        
        self._control_signals.append(control_signal)
    
    def evaluate(self, t: float, control_values: np.ndarray = None) -> np.ndarray:
        """
        Evaluate control Hamiltonian at time t.
        
        Ĥ_ctrl(t) = Σ_k u_k(t) Ĝ_k
        """
        self._matrix = np.zeros((self.dimension, self.dimension), dtype=complex)
        
        for k, (gen, signal) in enumerate(zip(self._generators, self._control_signals)):
            if control_values is not None and k < len(control_values):
                u_k = control_values[k]
            else:
                u_k = signal(t)
            
            self._matrix += u_k * gen.matrix
        
        return self._matrix.copy()
    
    def propagator(self, t: float, dt: float,
                   control_values: np.ndarray = None) -> np.ndarray:
        """
        Compute unitary propagator.
        
        U(dt) = exp(-i Ĥ_ctrl dt / ℏ)
        """
        H = self.evaluate(t, control_values)
        return linalg.expm(-1j * H * dt)
    
    def evolve_state(self, state: np.ndarray, t: float, dt: float,
                     control_values: np.ndarray = None) -> np.ndarray:
        """
        Evolve state under control Hamiltonian.
        
        |Ψ(t+dt)⟩ = U(dt)|Ψ(t)⟩
        """
        U = self.propagator(t, dt, control_values)
        return U @ state
    
    @property
    def num_channels(self) -> int:
        return len(self._generators)
    
    @property
    def matrix(self) -> np.ndarray:
        return self._matrix.copy()

# =============================================================================
# ACTUATOR OPERATOR
# =============================================================================

class ActuatorOperator:
    """
    The Actuator Operator Â.
    
    Translates classical control signal u(t) into quantum
    mechanical operator Ĥ_ctrl(t).
    
    Physical Implementation:
    - Phase Correction: If error is phase lag Δφ, apply V̂ = u(t)n̂
    - Trajectory Correction: If error is spatial drift Δx, apply P̂ = u(t)p̂
    """
    
    def __init__(self, dimension: int,
                 actuator_type: ActuatorType = ActuatorType.UNITARY):
        self.dimension = dimension
        self.actuator_type = actuator_type
        
        # Control Hamiltonian
        self.H_ctrl = ControlHamiltonian(dimension)
        
        # System Hamiltonian (to be combined)
        self._H_sys = np.zeros((dimension, dimension), dtype=complex)
        
        # Coupling efficiency
        self._coupling = 1.0
        
        # Initialize based on type
        self._setup_actuator()
    
    def _setup_actuator(self) -> None:
        """Set up actuator based on type."""
        if self.actuator_type == ActuatorType.PHASE:
            gen = GeneratorOperator(self.dimension, "number")
            self.H_ctrl.add_control_channel(gen)
        
        elif self.actuator_type == ActuatorType.MOMENTUM:
            gen = GeneratorOperator(self.dimension, "momentum")
            self.H_ctrl.add_control_channel(gen)
        
        elif self.actuator_type == ActuatorType.POSITION:
            gen = GeneratorOperator(self.dimension, "position")
            self.H_ctrl.add_control_channel(gen)
        
        elif self.actuator_type == ActuatorType.AMPLITUDE:
            gen_raise = GeneratorOperator(self.dimension, "raising")
            gen_lower = GeneratorOperator(self.dimension, "lowering")
            self.H_ctrl.add_control_channel(gen_raise)
            self.H_ctrl.add_control_channel(gen_lower)
        
        elif self.actuator_type == ActuatorType.UNITARY:
            # General: position, momentum, and number
            for gen_type in ["position", "momentum", "number"]:
                gen = GeneratorOperator(self.dimension, gen_type)
                self.H_ctrl.add_control_channel(gen)
    
    def set_system_hamiltonian(self, H_sys: np.ndarray) -> None:
        """Set the base system Hamiltonian."""
        self._H_sys = H_sys.copy()
    
    def total_hamiltonian(self, t: float,
                         control: np.ndarray = None) -> np.ndarray:
        """
        Compute total Hamiltonian.
        
        Ĥ_total(t) = Ĥ_sys + Ĥ_ctrl(t)
        """
        H_ctrl = self.H_ctrl.evaluate(t, control)
        return self._H_sys + self._coupling * H_ctrl
    
    def apply_control(self, state: np.ndarray, control: np.ndarray,
                      t: float, dt: float) -> np.ndarray:
        """
        Apply control to state.
        
        |Ψ(t+dt)⟩ = exp(-i Ĥ_total dt)|Ψ(t)⟩
        """
        H_total = self.total_hamiltonian(t, control)
        U = linalg.expm(-1j * H_total * dt)
        return U @ state
    
    def force(self, control: np.ndarray, t: float) -> np.ndarray:
        """
        Compute "force" from control signal.
        
        Force is related to generator expectation values.
        """
        H_ctrl = self.H_ctrl.evaluate(t, control)
        
        # Force magnitude related to Hamiltonian norm
        return np.linalg.norm(H_ctrl) * np.ones(len(control))
    
    def set_coupling(self, coupling: float) -> None:
        """Set actuator coupling efficiency."""
        self._coupling = coupling
    
    def add_custom_channel(self, generator_type: str) -> None:
        """Add custom control channel."""
        gen = GeneratorOperator(self.dimension, generator_type)
        self.H_ctrl.add_control_channel(gen)

# =============================================================================
# MODULATED ACTUATOR
# =============================================================================

class ModulatedActuator(ActuatorOperator):
    """
    Actuator with time-dependent modulation.
    
    Control signal: u(t) = A(t) × carrier(t)
    
    Where carrier can be constant, harmonic, pulse, or optimal.
    """
    
    def __init__(self, dimension: int,
                 modulation_type: ModulationType = ModulationType.HARMONIC,
                 **kwargs):
        super().__init__(dimension, **kwargs)
        
        self.modulation_type = modulation_type
        
        # Modulation parameters
        self._amplitude = 1.0
        self._frequency = 1.0
        self._phase = 0.0
        self._pulse_width = 1.0
    
    def carrier(self, t: float) -> float:
        """Generate carrier signal."""
        if self.modulation_type == ModulationType.CONSTANT:
            return 1.0
        
        elif self.modulation_type == ModulationType.HARMONIC:
            return np.cos(self._frequency * t + self._phase)
        
        elif self.modulation_type == ModulationType.PULSE:
            period = 2 * np.pi / self._frequency
            t_mod = t % period
            return 1.0 if t_mod < self._pulse_width else 0.0
        
        elif self.modulation_type == ModulationType.CHIRP:
            # Linear chirp
            instantaneous_freq = self._frequency * (1 + t)
            return np.cos(instantaneous_freq * t + self._phase)
        
        return 1.0
    
    def modulated_control(self, base_control: np.ndarray, t: float) -> np.ndarray:
        """
        Apply modulation to base control signal.
        
        u(t) = A × base × carrier(t)
        """
        return self._amplitude * base_control * self.carrier(t)
    
    def apply_modulated_control(self, state: np.ndarray,
                                base_control: np.ndarray,
                                t: float, dt: float) -> np.ndarray:
        """Apply modulated control to state."""
        modulated = self.modulated_control(base_control, t)
        return self.apply_control(state, modulated, t, dt)
    
    def set_modulation_params(self, amplitude: float = None,
                              frequency: float = None,
                              phase: float = None,
                              pulse_width: float = None) -> None:
        """Set modulation parameters."""
        if amplitude is not None:
            self._amplitude = amplitude
        if frequency is not None:
            self._frequency = frequency
        if phase is not None:
            self._phase = phase
        if pulse_width is not None:
            self._pulse_width = pulse_width

# =============================================================================
# OPTIMAL ACTUATOR
# =============================================================================

class OptimalActuator(ActuatorOperator):
    """
    Actuator with optimal control pulse design.
    
    Uses GRAPE (Gradient Ascent Pulse Engineering) or
    similar methods to find optimal control sequence.
    """
    
    def __init__(self, dimension: int, target_state: np.ndarray = None,
                 **kwargs):
        super().__init__(dimension, **kwargs)
        
        self._target = target_state
        self._optimal_pulses: List[np.ndarray] = []
        self._pulse_times: np.ndarray = None
    
    def set_target(self, target_state: np.ndarray) -> None:
        """Set target state for optimization."""
        self._target = target_state / np.linalg.norm(target_state)
    
    def fidelity(self, final_state: np.ndarray) -> float:
        """
        Compute fidelity with target.
        
        F = |⟨target|final⟩|²
        """
        if self._target is None:
            return 0.0
        
        overlap = np.abs(np.conj(self._target) @ final_state) ** 2
        return float(overlap)
    
    def optimize_pulse(self, initial_state: np.ndarray,
                       total_time: float, num_steps: int = 100,
                       iterations: int = 100) -> Dict:
        """
        Optimize control pulse using gradient ascent.
        
        Simple GRAPE implementation.
        """
        if self._target is None:
            raise ValueError("Target state not set")
        
        dt = total_time / num_steps
        self._pulse_times = np.linspace(0, total_time, num_steps)
        
        # Initialize random pulses
        num_channels = self.H_ctrl.num_channels
        pulses = 0.1 * np.random.randn(num_steps, num_channels)
        
        # Learning rate
        lr = 0.1
        
        best_fidelity = 0.0
        best_pulses = pulses.copy()
        
        for iteration in range(iterations):
            # Forward propagation
            states = [initial_state.copy()]
            state = initial_state.copy()
            
            for step in range(num_steps):
                state = self.apply_control(state, pulses[step], 
                                          self._pulse_times[step], dt)
                states.append(state.copy())
            
            # Compute fidelity
            fidelity = self.fidelity(state)
            
            if fidelity > best_fidelity:
                best_fidelity = fidelity
                best_pulses = pulses.copy()
            
            # Gradient computation (finite differences)
            gradients = np.zeros_like(pulses)
            eps = 1e-6
            
            for step in range(num_steps):
                for ch in range(num_channels):
                    pulses_plus = pulses.copy()
                    pulses_plus[step, ch] += eps
                    
                    # Propagate with perturbed pulse
                    state_plus = initial_state.copy()
                    for s in range(num_steps):
                        state_plus = self.apply_control(
                            state_plus, pulses_plus[s],
                            self._pulse_times[s], dt)
                    
                    fid_plus = self.fidelity(state_plus)
                    gradients[step, ch] = (fid_plus - fidelity) / eps
            
            # Update pulses
            pulses += lr * gradients
            
            # Clip pulses
            pulses = np.clip(pulses, -1.0, 1.0)
        
        self._optimal_pulses = [best_pulses[i] for i in range(num_steps)]
        
        return {
            "fidelity": best_fidelity,
            "iterations": iterations,
            "num_steps": num_steps,
            "pulses": best_pulses
        }
    
    def get_optimal_control(self, t: float) -> np.ndarray:
        """Get optimal control at time t."""
        if self._pulse_times is None or len(self._optimal_pulses) == 0:
            return np.zeros(self.H_ctrl.num_channels)
        
        # Find nearest time index
        idx = np.searchsorted(self._pulse_times, t)
        idx = min(idx, len(self._optimal_pulses) - 1)
        
        return self._optimal_pulses[idx]

# =============================================================================
# VALIDATION
# =============================================================================

def validate_actuators() -> bool:
    """Validate actuators module."""
    
    # Test GeneratorOperator
    gen_pos = GeneratorOperator(4, "position")
    gen_mom = GeneratorOperator(4, "momentum")
    
    assert gen_pos.is_hermitian()
    
    comm = gen_pos.commutator(gen_mom)
    assert comm.shape == (4, 4)
    
    # Test ControlHamiltonian
    H_ctrl = ControlHamiltonian(4)
    H_ctrl.add_control_channel(gen_pos)
    H_ctrl.add_control_channel(gen_mom)
    
    H = H_ctrl.evaluate(t=0.0, control_values=np.array([1.0, 0.5]))
    assert H.shape == (4, 4)
    
    U = H_ctrl.propagator(t=0.0, dt=0.1, control_values=np.array([1.0, 0.5]))
    assert U.shape == (4, 4)
    
    # Check unitarity
    assert np.allclose(U @ U.conj().T, np.eye(4), atol=1e-10)
    
    # Test ActuatorOperator
    actuator = ActuatorOperator(4, ActuatorType.UNITARY)
    
    state = np.array([1, 0, 0, 0], dtype=complex)
    state = state / np.linalg.norm(state)
    
    control = np.array([0.1, 0.2, 0.3])
    new_state = actuator.apply_control(state, control, t=0.0, dt=0.1)
    
    # Check normalization preserved
    assert np.abs(np.linalg.norm(new_state) - 1.0) < 1e-10
    
    # Test ModulatedActuator
    mod_actuator = ModulatedActuator(4, ModulationType.HARMONIC)
    mod_actuator.set_modulation_params(amplitude=0.5, frequency=2.0)
    
    carrier = mod_actuator.carrier(0.0)
    assert isinstance(carrier, float)
    
    modulated = mod_actuator.modulated_control(np.array([1.0, 1.0, 1.0]), t=0.0)
    assert len(modulated) == 3
    
    # Test OptimalActuator
    opt_actuator = OptimalActuator(2)
    
    initial = np.array([1, 0], dtype=complex)
    target = np.array([0, 1], dtype=complex)
    
    opt_actuator.set_target(target)
    
    fid = opt_actuator.fidelity(initial)
    assert 0 <= fid <= 1
    
    return True

if __name__ == "__main__":
    print("Validating Actuators Module...")
    assert validate_actuators()
    print("✓ Actuators Module validated")
