# CRYSTAL: Xi108:W2:A6:S18 | face=S | node=165 | depth=2 | phase=Cardinal
# METRO: Me
# BRIDGES: Xi108:W2:A6:S17→Xi108:W2:A6:S19→Xi108:W1:A6:S18→Xi108:W3:A6:S18→Xi108:W2:A5:S18→Xi108:W2:A7:S18

"""
ATHENA OS - BHAGAVAD GĪTĀ COMPUTATIONAL FRAMEWORK
==================================================
Part II: The Guṇas (Differential Operators)

THE UNIVERSAL HAMILTONIAN:
    Ĥ_Prakṛti = α(t)Ŝ + β(t)R̂ + γ(t)T̂
    
    Where α, β, γ determine the local phase of the simulation.

THE THREE OPERATORS:

SATTVA (Ŝ) - The Curl Operator (∇×):
    - Equilibrium, Signal, Circulation
    - Divergence-free (∇·(∇×v) = 0)
    - Workless force (zero energy dissipation)
    - Generates frequency and light

RAJAS (R̂) - The Gradient Operator (∇):
    - Force, Translation, Kinetic Energy
    - Positive divergence (source of flux)
    - Introduces time derivative (dψ/dt ≠ 0)
    - Power of Projection (Vikṣepa-Śakti)

TAMAS (T̂) - The Laplacian Operator (∇²):
    - Inertia, Mass, Resistance
    - Mass generation (∇²Φ ∝ ρ)
    - Diffusion and obscuration
    - Potential storage (Vāsanās)

THE 24 TATTVAS:
    Generated by cascading operator applications on Prakṛti.

SOURCES:
    The Bhagavad Gītā: A Computational Treatise
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List, Tuple, Optional, Callable
from enum import Enum, auto
import numpy as np
from scipy.linalg import expm
from scipy.ndimage import laplace

# =============================================================================
# GUNA TYPES
# =============================================================================

class GunaType(Enum):
    """The three fundamental Guṇas."""
    
    SATTVA = (2, "signal", "∇×", "Curl - Equilibrium/Circulation")
    RAJAS = (1, "force", "∇", "Gradient - Force/Translation")
    TAMAS = (0, "mass", "∇²", "Laplacian - Inertia/Storage")
    
    def __init__(self, level: int, comp_type: str, 
                 operator: str, description: str):
        self.level = level
        self.comp_type = comp_type
        self.operator_symbol = operator
        self.description = description

class TattvaCategory(Enum):
    """The 24 Tattva categories (Sāṅkhya)."""
    
    # Antaḥkaraṇa (Internal Instrument) - Sattva dominant
    BUDDHI = ("intelligence", GunaType.SATTVA, "Pure reflectivity")
    AHAMKARA = ("ego", GunaType.RAJAS, "Active identification")
    MANAS = ("mind", GunaType.TAMAS, "Data buffering")
    
    # Jñānendriyas (Knowledge Senses) - 5 types
    SHROTRA = ("hearing", GunaType.SATTVA, "Sound perception")
    TVAK = ("touch", GunaType.SATTVA, "Tactile perception")
    CHAKSHU = ("sight", GunaType.SATTVA, "Visual perception")
    RASANA = ("taste", GunaType.SATTVA, "Gustatory perception")
    GHRANA = ("smell", GunaType.SATTVA, "Olfactory perception")
    
    # Karmendriyas (Action Organs) - 5 types
    VAK = ("speech", GunaType.RAJAS, "Verbal output")
    PANI = ("grasping", GunaType.RAJAS, "Manual manipulation")
    PADA = ("locomotion", GunaType.RAJAS, "Movement")
    PAYU = ("excretion", GunaType.RAJAS, "Elimination")
    UPASTHA = ("reproduction", GunaType.RAJAS, "Generation")
    
    # Tanmātras (Subtle Elements) - 5 types
    SHABDA = ("sound", GunaType.SATTVA, "Vibration quantum")
    SPARSHA = ("touch_subtle", GunaType.RAJAS, "Pressure quantum")
    RUPA = ("form", GunaType.SATTVA, "Light quantum")
    RASA = ("taste_subtle", GunaType.RAJAS, "Chemical quantum")
    GANDHA = ("smell_subtle", GunaType.TAMAS, "Molecular quantum")
    
    # Mahābhūtas (Gross Elements) - 5 types
    AKASHA = ("space", GunaType.SATTVA, "Ākāśa - Connectivity")
    VAYU = ("air", GunaType.RAJAS, "Vāyu - Mobility")
    AGNI = ("fire", GunaType.RAJAS, "Agni - Transformation")
    APAS = ("water", GunaType.TAMAS, "Āpas - Cohesion")
    PRITHVI = ("earth", GunaType.TAMAS, "Pṛthvī - Solidity")
    
    def __init__(self, name: str, dominant_guna: GunaType, description: str):
        self._name = name
        self.dominant_guna = dominant_guna
        self.description = description

# =============================================================================
# THE SATTVA OPERATOR (CURL)
# =============================================================================

@dataclass
class SattvaOperator:
    """
    Sattva (Ŝ) - The Curl Operator (∇×).
    
    Properties:
        1. Divergence-free: ∇·(∇×v) = 0 (no energy leak)
        2. Workless force: W = ∫F·dl = 0 (effortless action)
        3. Harmonic generation: creates frequency and light
    
    Computational: Optimization, efficient processing, return true
    """
    
    # Operator matrix (for discrete states)
    dimension: int = 4
    _matrix: np.ndarray = field(default=None, repr=False)
    
    def __post_init__(self):
        if self._matrix is None:
            # Rotation-like matrix (curl in discrete setting)
            # Anti-symmetric generator
            self._matrix = np.zeros((self.dimension, self.dimension), dtype=complex)
            for i in range(self.dimension - 1):
                self._matrix[i, i+1] = 1j
                self._matrix[i+1, i] = -1j
    
    def apply(self, psi: np.ndarray) -> np.ndarray:
        """Apply Sattva operator to state."""
        result = self._matrix @ psi[:self.dimension]
        return result
    
    def curl_3d(self, vector_field: np.ndarray) -> np.ndarray:
        """
        Apply curl to 3D vector field.
        
        ∇×F = (∂Fz/∂y - ∂Fy/∂z, 
               ∂Fx/∂z - ∂Fz/∂x, 
               ∂Fy/∂x - ∂Fx/∂y)
        """
        # Assuming vector_field has shape (nx, ny, nz, 3)
        Fx, Fy, Fz = vector_field[..., 0], vector_field[..., 1], vector_field[..., 2]
        
        # Compute derivatives using finite differences
        curl = np.zeros_like(vector_field)
        
        # ∂Fz/∂y - ∂Fy/∂z
        curl[..., 0] = np.gradient(Fz, axis=1) - np.gradient(Fy, axis=2)
        # ∂Fx/∂z - ∂Fz/∂x
        curl[..., 1] = np.gradient(Fx, axis=2) - np.gradient(Fz, axis=0)
        # ∂Fy/∂x - ∂Fx/∂y
        curl[..., 2] = np.gradient(Fy, axis=0) - np.gradient(Fx, axis=1)
        
        return curl
    
    @property
    def is_divergence_free(self) -> bool:
        """Verify ∇·(∇×) = 0 property."""
        # For discrete matrix: trace of skew-symmetric = 0
        return abs(np.trace(self._matrix)) < 1e-10
    
    def generate_frequency(self, omega: float, t: float) -> complex:
        """Generate harmonic oscillation e^(iωt)."""
        return np.exp(1j * omega * t)
    
    @property
    def prakasha(self) -> str:
        """Light/Illumination property."""
        return "prakāśa"  # Clarity, luminosity

# =============================================================================
# THE RAJAS OPERATOR (GRADIENT)
# =============================================================================

@dataclass
class RajasOperator:
    """
    Rajas (R̂) - The Gradient Operator (∇).
    
    Maps scalar potential field φ(x) into vector force field F(x).
    Generates linear displacement and velocity.
    
    Properties:
        1. Kinetic injection: introduces T = p²/2m
        2. Positive divergence: ∇·V > 0 (source of flux)
        3. Directionality: imposes specific vector direction
    
    Computational: while(loop), thread.start(), process_interrupt
    """
    
    dimension: int = 4
    _matrix: np.ndarray = field(default=None, repr=False)
    
    def __post_init__(self):
        if self._matrix is None:
            # Derivative-like matrix (gradient in discrete setting)
            # Forward difference operator
            self._matrix = np.zeros((self.dimension, self.dimension), dtype=complex)
            for i in range(self.dimension - 1):
                self._matrix[i, i] = -1
                self._matrix[i, i+1] = 1
    
    def apply(self, psi: np.ndarray) -> np.ndarray:
        """Apply Rajas operator to state."""
        result = self._matrix @ psi[:self.dimension]
        return result
    
    def gradient_3d(self, scalar_field: np.ndarray) -> np.ndarray:
        """
        Apply gradient to 3D scalar field.
        
        ∇φ = (∂φ/∂x, ∂φ/∂y, ∂φ/∂z)
        """
        grad = np.zeros((*scalar_field.shape, 3))
        grad[..., 0] = np.gradient(scalar_field, axis=0)
        grad[..., 1] = np.gradient(scalar_field, axis=1)
        grad[..., 2] = np.gradient(scalar_field, axis=2)
        return grad
    
    def kinetic_energy(self, momentum: np.ndarray, mass: float = 1.0) -> float:
        """Compute kinetic energy T = p²/2m."""
        p_squared = np.sum(np.abs(momentum)**2)
        return float(p_squared / (2 * mass))
    
    def divergence(self, vector_field: np.ndarray) -> np.ndarray:
        """
        Compute divergence ∇·F.
        
        Positive divergence indicates source (Vikṣepa-Śakti).
        """
        div = np.zeros(vector_field.shape[:-1])
        for i in range(vector_field.shape[-1]):
            div += np.gradient(vector_field[..., i], axis=i)
        return div
    
    def sankalpa(self, direction: np.ndarray) -> np.ndarray:
        """
        Impose intention/direction vector.
        
        The power of "desire" or "will".
        """
        # Normalize to unit vector
        norm = np.linalg.norm(direction)
        if norm > 0:
            return direction / norm
        return direction
    
    @property
    def pravritta(self) -> str:
        """Activity/Projection property."""
        return "pravṛtta"  # Outward-moving, active

# =============================================================================
# THE TAMAS OPERATOR (LAPLACIAN)
# =============================================================================

@dataclass
class TamasOperator:
    """
    Tamas (T̂) - The Laplacian Operator (∇²).
    
    Represents divergence of gradient - second derivative of field.
    Governs curvature, density, and localization.
    
    Properties:
        1. Mass generation: ∇²Φ ∝ ρ (density)
        2. Diffusion: smoothes extrema (creates Avidyā)
        3. Potential storage: stores energy as U (Vāsanās)
    
    Computational: save_to_disk, sleep(), buffer_overflow
    """
    
    dimension: int = 4
    _matrix: np.ndarray = field(default=None, repr=False)
    
    def __post_init__(self):
        if self._matrix is None:
            # Laplacian-like matrix (second derivative)
            # Discrete Laplacian: [1, -2, 1] stencil
            self._matrix = np.zeros((self.dimension, self.dimension), dtype=complex)
            for i in range(self.dimension):
                self._matrix[i, i] = -2
                if i > 0:
                    self._matrix[i, i-1] = 1
                if i < self.dimension - 1:
                    self._matrix[i, i+1] = 1
    
    def apply(self, psi: np.ndarray) -> np.ndarray:
        """Apply Tamas operator to state."""
        result = self._matrix @ psi[:self.dimension]
        return result
    
    def laplacian_3d(self, scalar_field: np.ndarray) -> np.ndarray:
        """
        Apply Laplacian to 3D scalar field.
        
        ∇²φ = ∂²φ/∂x² + ∂²φ/∂y² + ∂²φ/∂z²
        """
        return laplace(scalar_field)
    
    def mass_density(self, potential: np.ndarray, 
                     coupling: float = 1.0) -> np.ndarray:
        """
        Compute mass density from potential.
        
        ∇²Φ = 4πGρ (Poisson equation)
        """
        return self.laplacian_3d(potential) / (4 * np.pi * coupling)
    
    def diffuse(self, field: np.ndarray, alpha: float = 0.1, 
                steps: int = 1) -> np.ndarray:
        """
        Apply diffusion (heat equation).
        
        ∂u/∂t = α∇²u
        
        This creates Avidyā (ignorance) by blurring distinctions.
        """
        result = field.copy()
        for _ in range(steps):
            lap = self.laplacian_3d(result) if result.ndim >= 3 else self.apply(result)
            result = result + alpha * lap
        return result
    
    def store_vasana(self, weight: float, memory: np.ndarray) -> np.ndarray:
        """
        Store a Vāsanā (latent impression) in memory.
        
        Tamas acts as the "Hard Drive" (Citta).
        """
        # Add weight to memory matrix
        perturbation = weight * np.ones_like(memory)
        return memory + perturbation
    
    @property
    def gurutva(self) -> str:
        """Heaviness/Mass property."""
        return "gurutva"  # Weight, inertia

# =============================================================================
# THE UNIVERSAL HAMILTONIAN
# =============================================================================

@dataclass
class UniversalHamiltonian:
    """
    The Universal Hamiltonian of Prakṛti.
    
    Ĥ_Prakṛti = α(t)Ŝ + β(t)R̂ + γ(t)T̂
    
    Where the coefficients α, β, γ determine the local phase
    of the simulation (e.g., Satya Yuga vs. Kali Yuga).
    """
    
    dimension: int = 4
    
    # The three operators
    sattva: SattvaOperator = field(default=None)
    rajas: RajasOperator = field(default=None)
    tamas: TamasOperator = field(default=None)
    
    # Time-dependent coefficients
    alpha: float = 1.0  # Sattva coefficient
    beta: float = 1.0   # Rajas coefficient
    gamma: float = 1.0  # Tamas coefficient
    
    def __post_init__(self):
        if self.sattva is None:
            self.sattva = SattvaOperator(self.dimension)
        if self.rajas is None:
            self.rajas = RajasOperator(self.dimension)
        if self.tamas is None:
            self.tamas = TamasOperator(self.dimension)
    
    @property
    def hamiltonian_matrix(self) -> np.ndarray:
        """
        Construct the full Hamiltonian matrix.
        
        H = αS + βR + γT
        """
        H = (self.alpha * self.sattva._matrix +
             self.beta * self.rajas._matrix +
             self.gamma * self.tamas._matrix)
        return H
    
    def set_yuga_coefficients(self, yuga: str) -> None:
        """
        Set coefficients based on Yuga.
        
        Satya: High Sattva (4), Low Tamas (1)
        Kali: Low Sattva (1), High Tamas (4)
        """
        yuga_config = {
            "SATYA": (4.0, 1.0, 1.0),    # S=4, R=1, T=1
            "TRETA": (3.0, 2.0, 1.0),    # S=3, R=2, T=1
            "DVAPARA": (2.0, 2.0, 2.0),  # S=2, R=2, T=2
            "KALI": (1.0, 2.0, 4.0),     # S=1, R=2, T=4
        }
        
        if yuga in yuga_config:
            self.alpha, self.beta, self.gamma = yuga_config[yuga]
    
    def time_evolution_operator(self, dt: float) -> np.ndarray:
        """
        Compute time evolution operator U(dt) = exp(-iHdt).
        """
        H = self.hamiltonian_matrix
        return expm(-1j * H * dt)
    
    def evolve_state(self, psi: np.ndarray, dt: float) -> np.ndarray:
        """
        Evolve state by time dt.
        
        |ψ(t+dt)⟩ = U(dt)|ψ(t)⟩
        """
        U = self.time_evolution_operator(dt)
        evolved = U @ psi[:self.dimension]
        
        # Renormalize
        norm = np.linalg.norm(evolved)
        if norm > 0:
            evolved /= norm
        
        return evolved
    
    def expectation_value(self, psi: np.ndarray) -> Dict[str, float]:
        """
        Compute expectation values of each Guṇa.
        
        ⟨ψ|Ŝ|ψ⟩, ⟨ψ|R̂|ψ⟩, ⟨ψ|T̂|ψ⟩
        """
        psi_trunc = psi[:self.dimension]
        
        exp_S = np.real(np.vdot(psi_trunc, self.sattva._matrix @ psi_trunc))
        exp_R = np.real(np.vdot(psi_trunc, self.rajas._matrix @ psi_trunc))
        exp_T = np.real(np.vdot(psi_trunc, self.tamas._matrix @ psi_trunc))
        
        return {
            "sattva": float(exp_S),
            "rajas": float(exp_R),
            "tamas": float(exp_T),
        }
    
    def dominant_guna(self, psi: np.ndarray) -> GunaType:
        """Determine the dominant Guṇa for a state."""
        exp_vals = self.expectation_value(psi)
        
        max_key = max(exp_vals, key=lambda k: abs(exp_vals[k]))
        
        guna_map = {
            "sattva": GunaType.SATTVA,
            "rajas": GunaType.RAJAS,
            "tamas": GunaType.TAMAS,
        }
        
        return guna_map[max_key]

# =============================================================================
# THE 24 TATTVA EVOLUTION
# =============================================================================

@dataclass
class TattvaEvolution:
    """
    Evolution of the 24 Tattvas from Prakṛti.
    
    The cascade of operator applications that generates
    the complete manifest reality.
    """
    
    hamiltonian: UniversalHamiltonian = field(default_factory=UniversalHamiltonian)
    
    def evolve_antahkarana(self, prakrti_state: np.ndarray) -> Dict[str, np.ndarray]:
        """
        Evolve the Internal Instrument (Antaḥkaraṇa).
        
        - Buddhi ← Pure Sattva (reflectivity)
        - Ahaṃkāra ← Rajas on Sattva (identification)
        - Manas ← Tamas on Sattva (buffering)
        """
        S = self.hamiltonian.sattva
        R = self.hamiltonian.rajas
        T = self.hamiltonian.tamas
        
        buddhi = S.apply(prakrti_state)
        ahamkara = R.apply(S.apply(prakrti_state))
        manas = T.apply(S.apply(prakrti_state))
        
        return {
            "buddhi": buddhi,
            "ahamkara": ahamkara,
            "manas": manas,
        }
    
    def evolve_indriyas(self, ahamkara_state: np.ndarray) -> Dict[str, np.ndarray]:
        """
        Evolve the Sense Organs from Ahaṃkāra.
        
        Jñānendriyas (5) - Sattva dominant
        Karmendriyas (5) - Rajas dominant
        """
        S = self.hamiltonian.sattva
        R = self.hamiltonian.rajas
        
        # Simplified: single representative for each class
        jnanendriyas = S.apply(ahamkara_state)
        karmendriyas = R.apply(ahamkara_state)
        
        return {
            "jnanendriyas": jnanendriyas,
            "karmendriyas": karmendriyas,
        }
    
    def evolve_tanmatras(self, ahamkara_state: np.ndarray) -> Dict[str, np.ndarray]:
        """
        Evolve the Subtle Elements (Tanmātras).
        
        5 subtle quanta: Śabda, Sparśa, Rūpa, Rasa, Gandha
        """
        # Each tanmātra is a specific modal evolution
        tanmatras = {}
        
        for i, name in enumerate(["shabda", "sparsha", "rupa", "rasa", "gandha"]):
            # Phase shift for each
            phase = 2 * np.pi * i / 5
            rotated = ahamkara_state * np.exp(1j * phase)
            tanmatras[name] = rotated
        
        return tanmatras
    
    def evolve_mahabhutas(self, tanmatra_states: Dict[str, np.ndarray]) -> Dict[str, np.ndarray]:
        """
        Evolve the Gross Elements (Mahābhūtas).
        
        The Pañcīkaraṇa (Quintuplication) process:
        Each element is 50% pure + 12.5% of each other element.
        """
        elements = ["akasha", "vayu", "agni", "apas", "prithvi"]
        tanmatra_list = ["shabda", "sparsha", "rupa", "rasa", "gandha"]
        
        mahabhutas = {}
        
        for i, elem in enumerate(elements):
            # Dominant eigenstate (50%)
            primary = tanmatra_states[tanmatra_list[i]] * 0.5
            
            # Entanglement terms (12.5% each)
            secondary = np.zeros_like(primary)
            for j, tanmatra in enumerate(tanmatra_list):
                if j != i:
                    secondary += tanmatra_states[tanmatra] * 0.125
            
            mahabhutas[elem] = primary + secondary
        
        return mahabhutas

# =============================================================================
# THE PANCHĪKARAṆA MATRIX
# =============================================================================

def panchakarana_matrix() -> np.ndarray:
    """
    The Pañcīkaraṇa (Quintuplication) Matrix.
    
    Π[i,j] = 0.5 if i==j else 0.125
    
    Each element is 50% dominant + 12.5% of each other.
    """
    Pi = np.ones((5, 5)) * 0.125
    np.fill_diagonal(Pi, 0.5)
    return Pi

# =============================================================================
# VALIDATION
# =============================================================================

def validate_gunas() -> bool:
    """Validate the gunas module."""
    
    # Test SattvaOperator
    S = SattvaOperator(dimension=4)
    assert S.is_divergence_free
    
    psi = np.array([1, 0, 0, 0], dtype=complex)
    result = S.apply(psi)
    assert len(result) == 4
    
    # Test frequency generation
    freq = S.generate_frequency(1.0, np.pi/2)
    assert abs(freq - 1j) < 1e-10
    
    # Test RajasOperator
    R = RajasOperator(dimension=4)
    result = R.apply(psi)
    assert len(result) == 4
    
    # Test kinetic energy
    p = np.array([1, 1, 1])
    ke = R.kinetic_energy(p, mass=1.0)
    assert abs(ke - 1.5) < 1e-10
    
    # Test TamasOperator
    T = TamasOperator(dimension=4)
    result = T.apply(psi)
    assert len(result) == 4
    
    # Test diffusion
    field = np.ones(4, dtype=complex)
    diffused = T.diffuse(field, alpha=0.1, steps=1)
    assert len(diffused) == 4
    
    # Test UniversalHamiltonian
    H = UniversalHamiltonian(dimension=4)
    
    # Test Yuga configuration
    H.set_yuga_coefficients("SATYA")
    assert H.alpha == 4.0
    assert H.gamma == 1.0
    
    H.set_yuga_coefficients("KALI")
    assert H.alpha == 1.0
    assert H.gamma == 4.0
    
    # Test time evolution
    psi = np.array([1, 0, 0, 0], dtype=complex)
    evolved = H.evolve_state(psi, 0.1)
    assert abs(np.linalg.norm(evolved) - 1.0) < 1e-10
    
    # Test expectation values
    exp_vals = H.expectation_value(psi)
    assert "sattva" in exp_vals
    assert "rajas" in exp_vals
    assert "tamas" in exp_vals
    
    # Test dominant guna
    dom = H.dominant_guna(psi)
    assert isinstance(dom, GunaType)
    
    # Test Pañcīkaraṇa matrix
    Pi = panchakarana_matrix()
    assert Pi.shape == (5, 5)
    assert abs(np.sum(Pi[0, :]) - 1.0) < 1e-10  # Rows sum to 1
    
    # Test TattvaEvolution
    tattva = TattvaEvolution()
    prakrti = np.array([1, 1, 1, 1], dtype=complex) / 2
    antahkarana = tattva.evolve_antahkarana(prakrti)
    assert "buddhi" in antahkarana
    assert "ahamkara" in antahkarana
    assert "manas" in antahkarana
    
    return True

if __name__ == "__main__":
    print("Validating Guṇas Module...")
    assert validate_gunas()
    print("✓ Guṇas module validated")
    
    # Demo
    print("\n--- Guṇas (Differential Operators) Demo ---")
    
    print("\n1. The Three Operators:")
    for guna in GunaType:
        print(f"   {guna.name}: {guna.operator_symbol} - {guna.description}")
    
    print("\n2. Universal Hamiltonian:")
    H = UniversalHamiltonian(dimension=4)
    H.set_yuga_coefficients("SATYA")
    print(f"   Satya Yuga: α={H.alpha}, β={H.beta}, γ={H.gamma}")
    H.set_yuga_coefficients("KALI")
    print(f"   Kali Yuga: α={H.alpha}, β={H.beta}, γ={H.gamma}")
    
    print("\n3. State Evolution:")
    psi = np.array([1, 0, 0, 0], dtype=complex)
    evolved = H.evolve_state(psi, 0.5)
    print(f"   Initial: {psi}")
    print(f"   After dt=0.5: {np.round(evolved, 3)}")
    
    print("\n4. Guṇa Expectation Values:")
    exp_vals = H.expectation_value(evolved)
    for guna, val in exp_vals.items():
        print(f"   ⟨{guna.capitalize()}⟩ = {val:.4f}")
    
    print("\n5. Pañcīkaraṇa Matrix (5×5):")
    Pi = panchakarana_matrix()
    print(f"   Diagonal: {np.diag(Pi)}")
    print(f"   Off-diagonal: {Pi[0, 1]}")
