# CRYSTAL: Xi108:W2:A1:S13 | face=S | node=79 | depth=2 | phase=Cardinal
# METRO: Me
# BRIDGES: Xi108:W2:A1:S12→Xi108:W2:A1:S14→Xi108:W1:A1:S13→Xi108:W3:A1:S13→Xi108:W2:A2:S13

"""
ATHENA OS - BHAGAVAD GĪTĀ COMPUTATIONAL FRAMEWORK
==================================================
Part III: The Jīva Agent (The Soul-Process)

THE JĪVA AGENT:
    A Reinforcement Learning model trapped in a recursive Vāsanā loop,
    capable of self-modification via Yoga protocols.

THE FIVE KOSHAS (Sheaths):
    0. Annamaya  - Hardware (Physical body)
    1. Prāṇamaya - Power/Clock (Vital energy)
    2. Manomaya  - I/O Buffer (Mind/RAM)
    3. Vijñānamaya - Kernel/CPU (Intellect)
    4. Ānandamaya - BIOS/Seed (Bliss sheath)

THE KARMA TENSOR K_μν:
    - Sanchita: Total accumulated (Hard drive)
    - Prārabdha: Currently executing (Active process)
    - Āgāmi: New impulses (Future buffer)

THE CITTA (WEIGHT MATRIX):
    Storage medium for Vāsanās (latent impressions).
    W[s][a] represents tendency to take action a in state s.

SOURCES:
    The Bhagavad Gītā: A Computational Treatise
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List, Tuple, Optional, Any
from enum import Enum, auto
import numpy as np
from scipy.linalg import expm

# =============================================================================
# KOSHA LEVELS
# =============================================================================

class KoshaLevel(Enum):
    """The five sheaths (Pañca-Kosha)."""
    
    ANNAMAYA = (0, "hardware", "Physical body - Food sheath")
    PRANAMAYA = (1, "power_clock", "Vital energy - Breath sheath")
    MANOMAYA = (2, "io_buffer", "Mind - Mental sheath (RAM)")
    VIJNANAMAYA = (3, "kernel_cpu", "Intellect - Wisdom sheath (CPU)")
    ANANDAMAYA = (4, "bios_seed", "Bliss - Causal sheath (BIOS)")
    
    def __init__(self, level: int, comp_analog: str, description: str):
        self.level = level
        self.comp_analog = comp_analog
        self.description = description

# =============================================================================
# ACTION TYPES
# =============================================================================

class ActionGuna(Enum):
    """Guṇa classification of actions."""
    
    SATTVIC = (2, "dharmic", "Aligned with truth, selfless")
    RAJASIC = (1, "mixed", "Driven by desire, attached to result")
    TAMASIC = (0, "adharmic", "Harmful, ignorant, destructive")
    
    def __init__(self, level: int, name: str, description: str):
        self.level = level
        self._name = name
        self.description = description

@dataclass
class ActionVector:
    """An action with its properties."""
    
    action_id: int
    name: str
    guna_type: ActionGuna
    dharma_value: float      # Alignment with cosmic law (-1 to 1)
    pleasure_value: float    # Sensory gratification (0 to 1)
    karma_weight: float = 1.0  # How much karma it generates
    
    @property
    def resultant_karma(self) -> float:
        """
        Calculate karma generated by this action.
        
        Sattvic actions generate less binding karma.
        Tamasic actions generate heavy karma.
        """
        guna_factor = {
            ActionGuna.SATTVIC: 0.1,
            ActionGuna.RAJASIC: 1.0,
            ActionGuna.TAMASIC: 2.0,
        }
        
        return self.karma_weight * guna_factor[self.guna_type]

# =============================================================================
# THE KARMA TENSOR
# =============================================================================

@dataclass
class KarmaTensor:
    """
    The Karma Tensor K_μν.
    
    Encodes the 'pressure' the Jīva applies to the Field.
    
    Components:
        - Sanchita (Accumulated): Total stored karma
        - Prārabdha (Active): Currently executing portion
        - Āgāmi (Future): New karma being created
    
    Operations:
        - Diagonalization (Yoga): Uncouples complex dependencies
        - Nullification (Mokṣa): Zeroes the entire tensor
    """
    
    dimension: int = 4
    
    # The three karma components (Rank-2 tensors)
    sanchita: np.ndarray = field(default=None, repr=False)    # Total
    prarabdha: np.ndarray = field(default=None, repr=False)   # Active
    agami: np.ndarray = field(default=None, repr=False)       # New
    
    def __post_init__(self):
        if self.sanchita is None:
            # Initialize with some accumulated karma
            self.sanchita = np.random.randn(self.dimension, self.dimension)
            self.sanchita = (self.sanchita + self.sanchita.T) / 2  # Symmetric
        
        if self.prarabdha is None:
            # Subset of sanchita for current life
            self.prarabdha = self.sanchita * 0.1
        
        if self.agami is None:
            # Starts empty
            self.agami = np.zeros((self.dimension, self.dimension))
    
    @property
    def total_load(self) -> float:
        """
        Trace of the Tensor: The total 'Mass' of the Ego.
        
        This is the "gravitational" weight that binds the Jīva.
        """
        return float(np.trace(self.sanchita) +
                     np.trace(self.prarabdha) +
                     np.trace(self.agami))
    
    @property
    def eigenvalues(self) -> np.ndarray:
        """
        Eigenvalues of sanchita.
        
        Represent independent karma streams.
        """
        return np.linalg.eigvalsh(self.sanchita)
    
    def add_karma(self, action: ActionVector, 
                  state_index: int = 0) -> float:
        """
        Add new karma from an action.
        
        Returns the karma added.
        """
        karma = action.resultant_karma
        
        # Add to āgāmi (future karma)
        self.agami[state_index, state_index] += karma
        
        # Off-diagonal for dependencies
        for i in range(self.dimension):
            if i != state_index:
                self.agami[state_index, i] += karma * 0.1
                self.agami[i, state_index] += karma * 0.1
        
        return karma
    
    def diagonalize(self) -> np.ndarray:
        """
        Yoga Operation: Diagonalize the sanchita tensor.
        
        Resolves off-diagonal dependencies into independent streams.
        This represents the 'Clarity' gained via meditation.
        
        Returns the eigenvalues (simplified karma streams).
        """
        eigenvals, eigenvecs = np.linalg.eigh(self.sanchita)
        self.sanchita = np.diag(eigenvals)
        
        # Also partially diagonalize prarabdha
        eigenvals_p, _ = np.linalg.eigh(self.prarabdha)
        self.prarabdha = np.diag(eigenvals_p)
        
        return eigenvals
    
    def burn_prarabdha(self, amount: float = 0.1) -> float:
        """
        Burn off active karma through experience.
        
        Returns amount burned.
        """
        burned = min(amount, np.trace(self.prarabdha))
        
        # Reduce diagonal uniformly
        for i in range(self.dimension):
            reduction = min(self.prarabdha[i, i], amount / self.dimension)
            self.prarabdha[i, i] -= reduction
        
        return burned
    
    def transfer_agami_to_sanchita(self) -> None:
        """
        At end of life, āgāmi transfers to sanchita.
        """
        self.sanchita += self.agami
        self.agami = np.zeros_like(self.agami)
    
    def nullify(self) -> None:
        """
        Mokṣa Operation: Zero all karma.
        
        The tensor becomes null, releasing the Jīva.
        """
        self.sanchita.fill(0)
        self.prarabdha.fill(0)
        self.agami.fill(0)
    
    def is_nullified(self, tolerance: float = 1e-10) -> bool:
        """Check if karma tensor is effectively zero."""
        return self.total_load < tolerance

# =============================================================================
# THE CITTA (MEMORY SYSTEM)
# =============================================================================

@dataclass
class Citta:
    """
    The Citta: Database of Vāsanās (latent impressions).
    
    Implemented as a weight matrix W[s][a] representing the
    tendency to take action a in state s.
    
    In RL terms: the policy network weights.
    """
    
    num_states: int = 16
    num_actions: int = 4
    
    # Weight matrix (Vāsanā storage)
    weights: np.ndarray = field(default=None, repr=False)
    
    # Learning rate for updating weights
    learning_rate: float = 0.1
    
    def __post_init__(self):
        if self.weights is None:
            # Initialize with small random weights
            self.weights = np.random.randn(self.num_states, self.num_actions) * 0.1
    
    def get_action_probabilities(self, state: int) -> np.ndarray:
        """
        Get probability distribution over actions for a state.
        
        Uses softmax over weights.
        """
        logits = self.weights[state, :]
        exp_logits = np.exp(logits - np.max(logits))  # Stability
        return exp_logits / np.sum(exp_logits)
    
    def select_action(self, state: int) -> int:
        """Sample an action based on current Vāsanās."""
        probs = self.get_action_probabilities(state)
        return int(np.random.choice(self.num_actions, p=probs))
    
    def update_vasana(self, state: int, action: int, 
                      reward: float) -> None:
        """
        Update Vāsanā weights based on experience.
        
        Positive reward strengthens the tendency.
        """
        self.weights[state, action] += self.learning_rate * reward
    
    def vasana_energy(self) -> float:
        """Total energy stored in Vāsanās."""
        return float(np.linalg.norm(self.weights))
    
    def clear_vasanas(self) -> None:
        """Purge all latent impressions (deep meditation)."""
        self.weights.fill(0)
    
    def is_sattvic(self) -> bool:
        """
        Check if Citta is predominantly Sattvic.
        
        Low total Vāsanā energy indicates purity.
        """
        return self.vasana_energy() < 0.1

# =============================================================================
# THE JĪVA AGENT
# =============================================================================

@dataclass
class Jiva:
    """
    The Jīva Agent.
    
    A Reinforcement Learning model trapped in a recursive Vāsanā loop,
    capable of self-modification via Yoga protocols.
    
    Components:
        - Ātman: Immutable pointer (witness consciousness)
        - Citta: Weight matrix (Vāsanā storage)
        - Karma: Tensor of accumulated actions
        - Koshas: The five sheaths
    """
    
    jiva_id: int = 0
    
    # Immutable components
    atman_id: int = 0  # Pointer to Brahman (never changes)
    
    # Mutable components
    citta: Citta = field(default_factory=Citta)
    karma: KarmaTensor = field(default_factory=KarmaTensor)
    
    # State
    current_state: int = 0
    current_kosha: KoshaLevel = KoshaLevel.MANOMAYA
    
    # Liberation status
    witness_mode: bool = False
    
    # Lifecycle
    birth_count: int = 0  # Number of rebirths
    
    def __post_init__(self):
        self.birth_count = 1  # This is first birth
    
    @property
    def is_liberated(self) -> bool:
        """Check if Jīva has achieved Mokṣa."""
        return self.witness_mode and self.karma.is_nullified()
    
    @property
    def is_jivanmukta(self) -> bool:
        """
        Jīvanmukta: Liberated while living.
        
        Witness mode active but still has prārabdha.
        """
        return self.witness_mode and not self.karma.is_nullified()
    
    def perceive(self, environment_state: int) -> int:
        """
        Perceive the environment through Koshas.
        
        Higher Koshas provide clearer perception.
        """
        # Add noise based on Kosha level
        noise_levels = {
            KoshaLevel.ANNAMAYA: 5,
            KoshaLevel.PRANAMAYA: 4,
            KoshaLevel.MANOMAYA: 3,
            KoshaLevel.VIJNANAMAYA: 2,
            KoshaLevel.ANANDAMAYA: 1,
        }
        
        noise = np.random.randint(-noise_levels[self.current_kosha],
                                   noise_levels[self.current_kosha] + 1)
        
        perceived = max(0, min(self.citta.num_states - 1, 
                               environment_state + noise))
        
        self.current_state = perceived
        return perceived
    
    def act(self, available_actions: List[ActionVector]) -> ActionVector:
        """
        Select and execute an action.
        
        In witness mode, actions generate no karma.
        """
        if self.witness_mode:
            # Sattvic action by default
            sattvic_actions = [a for a in available_actions 
                              if a.guna_type == ActionGuna.SATTVIC]
            if sattvic_actions:
                return sattvic_actions[0]
        
        # Select based on Vāsanās
        action_idx = self.citta.select_action(self.current_state)
        action_idx = min(action_idx, len(available_actions) - 1)
        
        selected = available_actions[action_idx]
        
        # Generate karma (unless in witness mode)
        if not self.witness_mode:
            self.karma.add_karma(selected, self.current_state)
        
        return selected
    
    def experience_result(self, action: ActionVector, 
                          reward: float) -> None:
        """
        Experience the result of an action.
        
        Updates Vāsanās and burns prārabdha.
        """
        # Update Citta
        self.citta.update_vasana(self.current_state, 
                                 action.action_id % self.citta.num_actions,
                                 reward)
        
        # Burn some prārabdha through experience
        self.karma.burn_prarabdha(abs(reward) * 0.01)
    
    def practice_yoga(self, intensity: float = 1.0) -> Dict[str, Any]:
        """
        Practice Yoga to purify the system.
        
        Effects:
            1. Diagonalize karma (simplify dependencies)
            2. Reduce Vāsanā energy
            3. Ascend to higher Kosha
        """
        results = {}
        
        # Diagonalize karma
        if intensity > 0.5:
            eigenvals = self.karma.diagonalize()
            results["karma_eigenvalues"] = eigenvals
        
        # Reduce Vāsanā energy
        reduction = intensity * 0.1
        self.citta.weights *= (1 - reduction)
        results["vasana_energy"] = self.citta.vasana_energy()
        
        # Possibly ascend Kosha
        if self.citta.vasana_energy() < 0.5:
            current_level = self.current_kosha.level
            if current_level < 4:
                self.current_kosha = KoshaLevel(
                    list(KoshaLevel)[current_level + 1]
                )
                results["ascended_to"] = self.current_kosha.name
        
        return results
    
    def enter_witness_mode(self) -> None:
        """
        Enter Sākṣī (Witness) state.
        
        Actions no longer generate karma.
        """
        self.witness_mode = True
    
    def attempt_moksha(self) -> bool:
        """
        Attempt final liberation.
        
        Requires:
            1. Witness mode active
            2. Vāsanās purified
            3. Karma nearly exhausted
        """
        if not self.witness_mode:
            return False
        
        if not self.citta.is_sattvic():
            return False
        
        if self.karma.total_load > 1.0:
            return False
        
        # Nullify remaining karma
        self.karma.nullify()
        
        return True
    
    def die_and_rebirth(self) -> 'Jiva':
        """
        Death subroutine: Context switch.
        
        - Āgāmi transfers to Sanchita
        - Prārabdha is reset from Sanchita
        - New body (Kosha reset)
        - Vāsanās preserved
        """
        # Transfer new karma to storage
        self.karma.transfer_agami_to_sanchita()
        
        # Allocate new prārabdha from sanchita
        allocation = min(0.2, np.trace(self.karma.sanchita))
        self.karma.prarabdha = np.eye(self.karma.dimension) * allocation / self.karma.dimension
        
        # Reset Kosha to physical
        self.current_kosha = KoshaLevel.ANNAMAYA
        
        # Vāsanās preserved (weights unchanged)
        
        # Increment birth count
        self.birth_count += 1
        
        return self

# =============================================================================
# THE DASHA SYSTEM
# =============================================================================

@dataclass
class DashaSystem:
    """
    The Cosmic Clock: Vimśottari Dasha System.
    
    Determines which Planetary Operator is active at any time.
    Each planet represents a specific mode of karma processing.
    """
    
    # Mahādashā periods in years
    PERIODS: Dict[str, int] = field(default_factory=lambda: {
        'KETU': 7, 'VENUS': 20, 'SUN': 6, 'MOON': 10, 'MARS': 7,
        'RAHU': 18, 'JUPITER': 16, 'SATURN': 19, 'MERCURY': 17
    })
    
    SEQUENCE: List[str] = field(default_factory=lambda: [
        'KETU', 'VENUS', 'SUN', 'MOON', 'MARS', 
        'RAHU', 'JUPITER', 'SATURN', 'MERCURY'
    ])
    
    # Total cycle length
    TOTAL_CYCLE: int = 120  # years
    
    # Current position in cycle
    current_year: float = 0.0
    
    # Birth position (determines initial dasha)
    birth_nakshatra_position: float = 0.0  # 0 to 1
    
    def __post_init__(self):
        # Calculate starting position based on birth
        total_so_far = 0
        for planet in self.SEQUENCE:
            total_so_far += self.PERIODS[planet]
        
        self.TOTAL_CYCLE = total_so_far
    
    def get_current_dasha(self) -> Tuple[str, float]:
        """
        Get current Mahādashā and phase within it.
        
        Returns (planet_name, phase_0_to_1)
        """
        # Offset by birth position
        adjusted_year = (self.current_year + 
                         self.birth_nakshatra_position * self.TOTAL_CYCLE)
        
        # Wrap around cycle
        cycle_position = adjusted_year % self.TOTAL_CYCLE
        
        # Find current dasha
        accumulated = 0
        for planet in self.SEQUENCE:
            period = self.PERIODS[planet]
            if accumulated + period > cycle_position:
                phase = (cycle_position - accumulated) / period
                return (planet, phase)
            accumulated += period
        
        return (self.SEQUENCE[0], 0.0)
    
    def get_planetary_operator(self) -> np.ndarray:
        """
        Get the Hamiltonian modifier for current dasha.
        
        Each planet has a characteristic operator.
        """
        planet, phase = self.get_current_dasha()
        
        # Simplified 4x4 operators for each planet
        operators = {
            'SUN': np.diag([1, 0.8, 0.6, 0.4]),      # Fire, authority
            'MOON': np.diag([0.5, 1, 0.5, 0.8]),     # Mind, fluctuation
            'MARS': np.diag([0.9, 0.9, 1, 0.3]),     # Energy, conflict
            'MERCURY': np.diag([0.7, 0.7, 0.7, 1]),  # Intellect, communication
            'JUPITER': np.diag([1, 1, 0.8, 0.9]),    # Expansion, wisdom
            'VENUS': np.diag([0.6, 1, 1, 0.7]),      # Pleasure, beauty
            'SATURN': np.diag([0.3, 0.4, 0.5, 1]),   # Restriction, karma
            'RAHU': np.diag([0.8, 0.6, 0.4, 0.9]),   # Obsession, shadow
            'KETU': np.diag([0.2, 0.3, 0.8, 0.5]),   # Liberation, detachment
        }
        
        return operators.get(planet, np.eye(4))
    
    def advance(self, years: float) -> str:
        """Advance time and return current dasha lord."""
        self.current_year += years
        planet, _ = self.get_current_dasha()
        return planet
    
    def apply_to_jiva(self, jiva: Jiva, dt: float = 0.1) -> None:
        """
        Apply dasha influence to a Jīva.
        
        Modulates karma processing rate.
        """
        operator = self.get_planetary_operator()
        
        # Modulate prārabdha burning rate
        planet, phase = self.get_current_dasha()
        
        # Saturn and Rahu slow karma burning
        if planet in ['SATURN', 'RAHU']:
            jiva.karma.burn_prarabdha(dt * 0.5)
        # Jupiter and Venus accelerate it
        elif planet in ['JUPITER', 'VENUS']:
            jiva.karma.burn_prarabdha(dt * 1.5)
        else:
            jiva.karma.burn_prarabdha(dt)

# =============================================================================
# VALIDATION
# =============================================================================

def validate_jiva() -> bool:
    """Validate the jiva module."""
    
    # Test ActionVector
    action = ActionVector(
        action_id=0, name="give", 
        guna_type=ActionGuna.SATTVIC,
        dharma_value=0.9, pleasure_value=0.3
    )
    karma = action.resultant_karma
    assert karma < 0.5  # Sattvic generates less karma
    
    # Test KarmaTensor
    kt = KarmaTensor(dimension=4)
    initial_load = kt.total_load
    assert initial_load != 0  # Should have initial karma
    
    # Add karma
    kt.add_karma(action, state_index=0)
    assert kt.total_load != initial_load
    
    # Diagonalize
    eigenvals = kt.diagonalize()
    assert len(eigenvals) == 4
    
    # Nullify
    kt.nullify()
    assert kt.is_nullified()
    
    # Test Citta
    citta = Citta(num_states=16, num_actions=4)
    probs = citta.get_action_probabilities(0)
    assert abs(sum(probs) - 1.0) < 1e-10
    
    action_idx = citta.select_action(0)
    assert 0 <= action_idx < 4
    
    initial_energy = citta.vasana_energy()
    citta.update_vasana(0, 0, 1.0)
    assert citta.vasana_energy() != initial_energy
    
    # Test Jiva
    jiva = Jiva(jiva_id=1)
    assert not jiva.is_liberated
    assert jiva.current_kosha == KoshaLevel.MANOMAYA
    
    # Test perception
    perceived = jiva.perceive(5)
    assert isinstance(perceived, int)
    
    # Test action
    actions = [
        ActionVector(0, "sattvic", ActionGuna.SATTVIC, 0.9, 0.3),
        ActionVector(1, "rajasic", ActionGuna.RAJASIC, 0.5, 0.7),
    ]
    selected = jiva.act(actions)
    assert isinstance(selected, ActionVector)
    
    # Test yoga
    results = jiva.practice_yoga(intensity=1.0)
    assert "vasana_energy" in results
    
    # Test witness mode
    jiva.enter_witness_mode()
    assert jiva.witness_mode
    
    # Test DashaSystem
    dasha = DashaSystem()
    planet, phase = dasha.get_current_dasha()
    assert planet in dasha.SEQUENCE
    assert 0 <= phase <= 1
    
    # Advance time
    new_planet = dasha.advance(10)
    assert new_planet in dasha.SEQUENCE
    
    return True

if __name__ == "__main__":
    print("Validating Jīva Module...")
    assert validate_jiva()
    print("✓ Jīva module validated")
    
    # Demo
    print("\n--- Jīva Agent Demo ---")
    
    print("\n1. Kosha Levels:")
    for kosha in KoshaLevel:
        print(f"   {kosha.level}. {kosha.name}: {kosha.comp_analog}")
    
    print("\n2. Creating Jīva Agent:")
    jiva = Jiva(jiva_id=42)
    print(f"   ID: {jiva.jiva_id}")
    print(f"   Current Kosha: {jiva.current_kosha.name}")
    print(f"   Initial Karma Load: {jiva.karma.total_load:.4f}")
    
    print("\n3. Karma Tensor:")
    print(f"   Sanchita trace: {np.trace(jiva.karma.sanchita):.4f}")
    print(f"   Prārabdha trace: {np.trace(jiva.karma.prarabdha):.4f}")
    print(f"   Āgāmi trace: {np.trace(jiva.karma.agami):.4f}")
    
    print("\n4. Performing Action:")
    action = ActionVector(0, "donate", ActionGuna.SATTVIC, 0.9, 0.2)
    jiva.act([action])
    print(f"   Karma after action: {jiva.karma.total_load:.4f}")
    
    print("\n5. Practicing Yoga:")
    results = jiva.practice_yoga(intensity=1.0)
    print(f"   Vāsanā energy: {results['vasana_energy']:.4f}")
    
    print("\n6. Dasha System:")
    dasha = DashaSystem()
    planet, phase = dasha.get_current_dasha()
    print(f"   Current Dasha Lord: {planet}")
    print(f"   Phase: {phase:.2%}")
